### ISSUE TITLE
Attributes not forwarded to AWS SP

### ISSUE THREAD

**Issue by walton-io** [senorkrabs/aws-saml-proxy#1]
Hello. Thanks so much for putting this repo together. 

What I am trying: 
Google/G-Suite as the SAML IDP 
AWS Workspaces as the SAML SP

in `satosa/config/plugins/backends/saml2_backend.yaml`
I had to set these the below to true 
```
  mirror_force_authn: true
  memorize_idp: true
```

When I try to hit my unsolicited link with a `target` param in the url, I can get to google and authenticate. 

Using the Chrome developer tools, I see the first SAMLResponse payload and that contains the correct attributes. 

However the second SAMLResponse that comes from `https://signin.aws.amazon.com/saml` tells me the SAML response is invalid. When I decode the base64 for this response I can see the attributes are missing. 

In the ECS/Fargate logs, I see something like `backend attributes received`  and I can also see logs relating to the custom nameID and attributes processor you have configured.  

I've spent some time digging and found other people having the same issue with satosa 

https://lists.sunet.se/hyperkitty/list/satosa-users@lists.sunet.se/thread/5CUGMZZ6TPNDTRCHV7IZOTQBGADPRV6N/

https://lists.sunet.se/hyperkitty/list/satosa-users@lists.sunet.se/thread/IIRFENYNCM2UR3GKOKV6AES4F2OWPBUG/

https://lists.sunet.se/hyperkitty/list/satosa-users@lists.sunet.se/thread/L6DHB5JROVGSFPULPPSFW7Y4XBDXEKUU/?sort=date

in my logs I see the below as well similar to the users in the links above 
```
Filter: []
returning attributes {}
```

I've also double checked the name_format coming from AWS ...everything looks fine but no attributes. 

I've trying playing with the frontend/backed yaml config but i am unable to get the attributes to the SP

**Comment by senorkrabs** [comment]
Hey there,

Thanks for reaching out. It's been several years since I've worked on this and I'm not sure if any changes to Satosa may have broken its functionality. That said, I think I ran into something similar when trying to pass AWS-specific attributes that were not in the attribute map. You may need to turn on debug logging for Satosa to catch this.

Here are the custom attributes maps I added: https://github.com/senorkrabs/aws-saml-proxy/blob/master/satosa/config/attributemaps/custom.py 

This is called out in the PySAML2 docs; https://pysaml2.readthedocs.io/en/latest/howto/config.html#attribute-map-dir 

Now if you're using this repo, the custom attributes/mappings for AWS-based attributes should already be in custom.py. However, if you're specifying other custom attributes they may not be there or perhaps the way these attribute maps are imported has changed.

**Comment by walton-io** [comment]
Hi thanks for getting back to me

Yeah I used your repo. It does show me that backend attributes are being mapped in the logs. 

I think something changed with satosa since this repo was created, I think they are 2 major versions a head now. 

Could this be related to modifying the idp XML before uploading it to the SP ?

The custom maps you put in work within reason cos I can see it converts my nameID to `domain/user.name`
its just when the request is forwarded to AWS attributes are missing from the SAMLResponse

The attributes you map/use are exactly the ones I need.

**Comment by walton-io** [comment]
For anyone else who got stuck...  This code works fine if you rebuild satosa v7.0.3 and use that in the dockerfile 

using `satosa/satosa:latest` breaks the attribute filter now. 


Thanks again @senorkrabs
